version: '3.7'

services:
  #MySQL Database 
  mysql-database-int: 
    container_name: mysql-database-forum
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
    - my-network
  
#Network
networks: 
  my-network:
    driver: bridge