 create table tb_topic (
    id bigint generated by default as identity,
    created_date timestamp,
    message varchar(255),
    status varchar(255),
    title varchar(255),
    author_id bigint,
    course_id bigint,
    primary key (id),
    foreign key(course_id) references tb_course(id),
    foreign key(author_id) references tb_user(id)
 );
