create table tb_answer (
    id bigint generated by default as identity,
    created_date timestamp,
    message varchar(255),
    resolved boolean not null,
    author_id bigint,
    topic_id bigint,
    primary key (id),
    foreign key (topic_id) references tb_topic(id),
    foreign key (author_id) references tb_user(id)
);